FROM python:3.8-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader punkt stopwords

EXPOSE 5000

ENV PORT 5000

CMD ["gunicorn", "--bind", "0.0.0.0:$PORT", "app:app"]
